apiVersion: apps/v1

kind: Deployment
metadata:
  name: api
  namespace: service
  labels:
    app: pod-api-deployment
spec:
  replicas: 1
  selector:
    matchLables:
      app: pod-api
  # pod templates
  template:
    metadata:
      labels:
        app: pod-api
        # 일부로 파일에 변경 내용이 생기게 함으로써 다른 내용이 같은 deployment 를 배포하더라도 다르게 인지할 수 있도록 하기 위한 변수
        # CI/CD tool 에서 변수를 할당
        date: $LABELDATE
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: pod-api
          imagePullPolicy: Always
          image: xxx
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 10
            initialDelaySeconds: 210
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 5
            initialDelaySeconds: 210
            periodSeconds: 5
            timeoutSeconds: 3